services:
  application-streamer-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4443:4443"
    networks:
      - default
    volumes:
      - ./application-streamer:/usr/bin/application_streamer/application-streamer
      - ./moq-async:/usr/bin/application_streamer/moq-async
      - ./moq-karp:/usr/bin/application_streamer/moq-karp
      - ./moq-native:/usr/bin/application_streamer/moq-native
      - ./moq-transfork:/usr/bin/application_streamer/moq-transfork
      - ./mp4-atom:/usr/bin/application_streamer/mp4-atom
      - ./Cargo-dev.toml:/usr/bin/application_streamer/Cargo.toml
      - ./Cargo.lock:/usr/bin/application_streamer/Cargo.lock
      - target:/usr/bin/application_streamer/target

networks:
  default:

volumes:
  target: