services:
  application-streamer-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4443:4443"
    network_mode: host
    volumes:
      - .:/usr/bin/application_streamer/
      - target:/usr/bin/application_streamer/target
      - dist:/usr/bin/application_streamer/dist
      - node_modules:/usr/bin/application_streamer/node_modules

volumes:
  target:
  dist:
  node_modules: